### ISSUE TITLE
Cache dependencies in Circle CI

### ISSUE THREAD

**Issue by tirkarthi** [fulcrologic/fulcro#195]
It seems the build downloads a lot of dependencies (around 347) from Maven and Clojars. Circle CI provides an option to cache the dependencies so that they don't need to be downloaded. I don't know if introducing caching will cause any discrepancy in tests but it's worth a try since it will reduce the load of downloading dependencies and possibly testing time where the actual testing part takes only around 2 seconds out of the 2 minutes in the build step.

Ref : https://circleci.com/docs/2.0/language-clojure/#sample-configuration

Relevant config : 

```yaml
   steps: # commands that comprise the `build` job
      - checkout # check out source code to working directory
      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: cci-demo-clojure-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
          key: cci-demo-clojure-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
```
